<?php


namespace App\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class DraftCommand extends Command
{
    // the name of the command (the part after "bin/console")
    protected static $defaultName = 'd:d';

    public function __construct(string $name = null)
    {
        parent::__construct($name);
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }



    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln("Its Draft command....\n\n");


        $a1=array("red","blue");
        $a2=array("blue","yellow");
        print_r(array_merge($a1,$a2));



    }


}